### ISSUE TITLE
Game tracking

### ISSUE THREAD

**Issue by Lorech** [Lorech/Collectathon#1]
The base of the entire application will be games. I figure the easiest way to track what you (don't) want to collect, or what you've already collected, would be by allowing just one game per system, and then filtering out unwanted collectibles.

The aim of this issue is to implement the base functionality for tracking and adding games to the system. No specific UI requirements are set yet, but the UI should be somewhat styled and usable.

**Comment by Lorech** [comment]
Progress tracker:
- [ ] Base UI for adding a new game is added
- [ ] Base UI for displaying available games is created
- [ ] Creation form is reused to implement game editing
- [ ] Unwanted games can be deleted
- [ ] Base UI is cleaned up to something more palletable
